### ISSUE TITLE
Crash when clicking search tab in creative with ExtrabiomesXL installed with TiC-Tooltips.

### ISSUE THREAD

**Issue by mine-my-own-bizz** [ExtrabiomesXL/ExtrabiomesXL#423]
Below is an issue I posted to the TiC-tooltips Git. I decided to post it here as well after Squeek502 recommended it.

" squeek502
Ah, I think I know why that's happening. Probably worth reporting to ExtraBiomesXL as well because it definitely shouldn't be possible to crash from calling getUnlocalizedName(), even if TiC Tooltips is doing something slightly incorrect (getting the name of a stack with OreDictionary.WILDCARD_VALUE metadata)."

Had this crash after updating TiCTooltips-mc1.7.10-1.1.11b to TiCTooltips-mc1.7.10-1.2.0 in a modpack I am working on currently.

I narrowed it down some...

With only the following mods installed;

-forge-1.7.10-10.13.2.1277-universal.jar
-Mantle-1.7.10-0.3.2.jar
-TConstruct-1.7.10-1.8.1.jar
-TiCTooltips-mc1.7.10-1.2.0.jar
-extrabiomesxl_1.7.10-3.16.0.jar

I get the following "shutting down internal server" warning crash.
http://pastebin.com/EJHGt82m

**Comment by Annysia** [comment]
I'll have the guys look at the logs you've posted,  but it could also be that you are using a way higher version of Forge than the recommended version and the version we have built against.

**Comment by mine-my-own-bizz** [comment]
Ok, sounds good. I still have the instance built in MultiMC. I can swap out Forge versions and test rather easily. Let me know if I can help test against any other Forge version(s).

**Comment by ScottKillen** [comment]
NotEnoughItems does the same thing...but Chickenbones anticipates a possible crash and catches the exception... If TIC Tooltips is going to pass potentially bad data, it should anticipate an exception and handle it.
