### ISSUE TITLE
Crash on game launch resulting from failure to register biomes

### ISSUE THREAD

**Issue by Morvelaira** [ExtrabiomesXL/ExtrabiomesXL#430]
Crash on game launch using the Minecraft Launcher.
Crash Report: http://pastebin.com/y4bbRLd0
Stack Trace: http://pastebin.com/HkhS5nP0

Added a new copy of EBXL 3.16.0 to a custom mix of mods I'm attempting to cobble together into a modpack. First time load with EBXL installed (having installed each new mod once at a time) gets the above error/crash 100%.

Other mods included in the pack currently are: http://pastebin.com/4mpj6kg2

**Comment by ScottKillen** [comment]
Morvy,

There is a bug in that version of Forge (1230) that crashes all biome mods. It is fixed in Forge build 1231.

* * *

Reference: MinecraftForge/MinecraftForge#1447

**Comment by Morvelaira** [comment]
Thank you for helping those of us less technically able! For future reference, did I put together the report well for you?

**Comment by ScottKillen** [comment]
Perfectly! :grinning:
