### ISSUE TITLE
Having tick lag when decorating "Temperate Rainforest" biome

### ISSUE THREAD

**Issue by utoc** [ExtrabiomesXL/ExtrabiomesXL#435]
Hi!

I've recently made the switch from BoP to ExtrabiomesXL and I have noticed an issue with tick lag in the game during worldgen.  I had trouble tracking this one down because I swapped out about 30 mods in my pack and wasn't quite sure which one might be causing it.  Today I think I have an answer.  I can fly around in creative and generate the world in relative peace.. the world generates 8-10 chunks ahead of me as it should.. until I come to a temporate rainforest biome.  When I enter one, aproximate 2-3 chunks into it, the world will freeze and my tickrate will chunk into the 20,000ms range and the game is essentially unplayable.  Once the chunks have finished decorating, all seems to be fine.

I really don't know how to troubleshoot this one any better.  sfPlayer's Sampler mod only points to "Worldgen" in the stall report and not specifically to Extrabiomes.  If you have any suggestions to help give you guys some factual information or something to go on, I am willing to help diagnose/troubleshoot this in any way.  Here is a stall report in case it can somehow help: http://pastebin.com/aGcrJS9k

I am running EXL 3.16.2, FML 1448.  A full mod list can be found here: https://www.reddit.com/r/BBQSauce/wiki/modlist

**Comment by keybounce** [comment]
Is this just the "leaf block generation and test for wood" issue?
Did you have any trouble with vanilla jungles?

**Comment by allaryin** [comment]
That is what this looks like - the blasted leaf generation...

**Comment by utoc** [comment]
@keybounce Do you mean jungle generation after EBXL is running or jungle generation when EBXL is not present?  I have never noticed any issues with vanilla jungles but I can take another look if that could help in some way.

@allaryin Is this a known issue then?  Sorry, I hate making duplicates.  Let me know if this needs to be closed.

**Comment by allaryin** [comment]
@utoc All leaves for major mods... inherit from vanilla's behavior. EBXL's leaf blocks are no different. Any very large forest with lots and lots of leaves will cause worldgen lag. The taller the trees, and the higher the elevation, the worse it gets. This is a bug in vanilla. I'm working on an alternative in the EBXS rewrite... but that's taking a long time.

If you can see if this happens when generating any other biomes, it would be appreciated.

**Comment by utoc** [comment]
@allaryin The snowy rainforest did this as well but it wasn't near the magnitude of the temperate rainforest.  I guess I never noticed this with Natura or Biomes o Plenty.  I've got the biome disabled for now.  Thanks for letting me know though.
