### ISSUE TITLE
Crash with EBXL 3.16.3 & Factorization 0.8.97

### ISSUE THREAD

**Issue by xeronut** [ExtrabiomesXL/ExtrabiomesXL#439]
http://pastebin.com/Awa2F1QS

This crash was worked around for FZ 0.8.98.  I'm attaching the report here for future reference in case this is an issue anywhere else before (or with) the EBXL rewrite.  Also, here is a link to neptunepink's reply in the MCF thread if this is useful:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284592-factorization-0-8-98?comment=2863

Thank you for your time!

**Comment by allaryin** [comment]
Interesting. I'll patch this from our end shortly.

**Comment by allaryin** [comment]
Duplicated with another mod (Veinminer). Testing the fix relative to that ticket.
