### ISSUE TITLE
Buildcraft and IC2 integration outdated

### ISSUE THREAD

**Issue by Adaptivity** [ExtrabiomesXL/ExtrabiomesXL#440]
Getting this in the log: http://pastebin.com/zbeCS7ma
If you are not going to fix this, can you at least hide these errors, so they will not spam the log?
Versions:
Buildcraft 7.0.22
extrabiomesxl_1.7.10-3.16.2
industrialcraft-2-2.2.770-experimental
Forge 1492

**Comment by allaryin** [comment]
With IC2 2.2.810, I do not see that error spam any more.
