### ISSUE TITLE
EssentialCraft and ExtraBiomes conflict

### ISSUE THREAD

**Issue by 1skandar** [ExtrabiomesXL/ExtrabiomesXL#441]
Unfortunately, I have no hard evidence because nothing is going to the logs but something has gone very wrong.

With both EssentialCraft and ExtraBiomes together villages almost do not spawn. You will get maybe 1 village in several thousand blocks and that village is ALWAYS just 2 structures. You also get massive, massive chunk ticking lag.

I'm not sure what is going on and I wish I could offer more hard evidence here, but something is decidedly screwy.

**Comment by Annysia** [comment]
We don't do anything that effects how villages spawn.  Chunk ticking lag is a vanilla issue that then can be made worse by mods like ours that add a lot of leaves/trees.  For the lag issue I recommend using Fast Craft.  With it installed I am running around 160 mods and the only time I experience lag is when going into a new area for the first time.

What versions of EB, Forge and MC are you using?  If you can post logs that might help us verify if EB is causing any issues.  I'm not familiar with EssentialCraft, so I can't speak to how it might be interacting with EB.
