### ISSUE TITLE
Gloriosa Vine Is Missing.

### ISSUE THREAD

**Issue by Xjela** [ExtrabiomesXL/ExtrabiomesXL#442]
http://imgur.com/a/DkpJ3
What should I do?

**Comment by allaryin** [comment]
Is the vine spawning in jungles with the broken texture?

**Comment by Xjela** [comment]
I saw them only in jungle and they are all have broken texture.

**Comment by allaryin** [comment]
Do you have a texturepack installed that could be interfering here?

**Comment by Xjela** [comment]
I dont use any texturepack. Its default.

**Comment by Annysia** [comment]
What version are you using?  We are seeing them on our server using the latest version of EB.

**Comment by allaryin** [comment]
I just double checked the official jar and the texture is in there, so it sounds like you're using either an old or a custom build.

**Comment by Xjela** [comment]
Im using 1.7.10 extrabiomesxl_3.16.3 version. Is it old?

**Comment by allaryin** [comment]
No, that is, in fact, the latest version. Did you or someone in your group compile it, or did you download it from curse?

**Comment by Xjela** [comment]
Yeah I downloaded it from Curse.

**Comment by allaryin** [comment]
I see the vines in inventory, in hand, and in world just fine using the latest version from curse:
![2015-10-23_08 54 05](https://cloud.githubusercontent.com/assets/56085/10694434/b07539b4-7963-11e5-80ec-815cf95b9b0f.png)
It sounds like you have something else going on - possible weird conflicts that I'm unaware of.

But first, I'd just try re-downloading it maybe? It also looks like you're missing localization text. What language do you have MC set to run in?

**Comment by Xjela** [comment]
And Im using this mod in my private modpack. Could it be caused by it?

**Comment by allaryin** [comment]
It is unlikely, but something in your modpack could be interfering, yes.

**Comment by Xjela** [comment]
Odd. Im using English. I will try re-download it.

**Comment by Xjela** [comment]
Anyway, I couldn't find the problem. Thanks for your care.
