### ISSUE TITLE
Server crash - ItemNewSappling

### ISSUE THREAD

**Issue by JasonMcRay** [ExtrabiomesXL/ExtrabiomesXL#444]
Crash: http://pastebin.com/zdnVVgb9

Would like to provide more detail, but there is not much. Looks like player logs onto server, and server crashes. If needed i guess I could provide inventory list of that player (if the data is not already gone)

Modpack (InfiTech 2) is using v3.16.3, but I dont see anything in changelog relevant to this crash in latest 3.16.4.

**Comment by allaryin** [comment]
That crash sounds like exactly what I fixed in 3.16.4 :) Except in this case it's MobiusCore iterating over saplings instead of Veinminer iterating over leaves. I would not be surprised if the current patch does already fix it, but I can double-check with sapling blocks to make sure on my end.

**Comment by JasonMcRay** [comment]
Oh... I will tell the server owner to update to latest.... and if he will be faster than you, i will let you know :)

**Comment by allaryin** [comment]
Sigh, confirmed that the update probably will not fix the error. I'll bang out a patch right now. Give me 30 minutes.

**Comment by allaryin** [comment]
I need to verify that this is the last time I'll have to make this kind of update, but will have a test build uploaded to Curse tonight or tomorrow.
