### ISSUE TITLE
Potential conflict with Twilight Forest

### ISSUE THREAD

**Issue by theblackwidower** [ExtrabiomesXL/ExtrabiomesXL#449]
Not sure whether to post this here, or if it's even relevant, but while running both this and Twilight Forest I ended up getting a Twilight Forest biome in the overworld.

![2016-06-29_05 16 34](https://cloud.githubusercontent.com/assets/8587433/16447476/d1502434-3dba-11e6-96ab-67567a161083.png)

I don't think this is supposed to happen. If you don't see this as a concern, I guess ignore my ramblings.

Running ExtrabiomesXL 3.16.4, Twilight Forest 2.3.7, and Forge 1.7.10-10.13.4.1614-1.7.10

**Comment by ScottKillen** [comment]
Normally, there is no conflict between Twilight Forest and ExtrabiomesXL and both run well together out of the box. You have not posted you logs, but I would bet you are also running Biomes 'O Plenty--and it has known biome ID conflicts with Twilight Forest. There are instruction elsewhere on how to fix this, but the solution involves assigning the Twilight Forest biomes different ids to remove the conflict.
