### ISSUE TITLE
What would be required to update to 1.10.2?

### ISSUE THREAD

**Issue by GuardedAirplane** [ExtrabiomesXL/ExtrabiomesXL#450]
I really enjoy this mod and want to use it in my 1.10.2 world. I know a little java and wanted to know what code must be modified to update to 1.10.2.

**Comment by Annysia** [comment]
It requires a significant update to the mod and probably close to a total rewrite.  We only have one person that codes for us and he doesn't have much time to work on this.

**Comment by allaryin** [comment]
The port is "underway" but like Annysia said, I don't have a lot of time to work on it - I made my last update 10 or 12 weeks ago, when I knocked it down to under 2500 compiler errors. It's a big mod.

Everything is checked in - so if you fork the 1.10 branch, you are more than welcome to give it a whirl... but "a little java" probably won't be enough. It's going to take a good bit of experience and just tons and tons of time to finish the port.
